data:
  size: [192, 256]
  crop: [0.1, 8.0]
  shuffle_c: False
  trainpath: 'data/svbrdf/train'
  testpath: 'data/svbrdf/test'
  use_only_first_n: -1        # for debug, when =-1, load all
  use_pretrained_encoder: False
  pretrained_encoder_dir: 'checkpts/'

model:
  mapping_layers: 0
  layers: 4
  w: 32
  z: 64

  renderer:
    fov: 45
    gamma: 2.2
    attenuation: True

  loss:
    gram: 1
    vggps: 0.001

train:
  bs: 1
  epochs: 1000001
  eval_every_n: 500
  logLoss_every_n: 10
  use_augmentation: True

meta:
  algorithm: 'fomaml'

  # innerloop steps and meta batchsize
  num_inner_steps: 20
  num_inner_tasks: 3

  # inner-optim parameters
  inner_optim: 'meta_sgd'           # sgd or meta_sgd
  inner_lr: 0.01
  init_metasgd: 0.001               # init for meta-sgd per-parameter learning rate

  # optim parameters
  outer_optim: 'adam'
  outer_lr: 1e-4
  minimum_lr: 1e-9
  weight_decay: 1e-6

  # loading checkpt:
  load_checkpt: False
  checkpt_path: 'checkpts/svbrdf.pt'